### ISSUE TITLE
Release ocaml-session.0.4.2

### ISSUE THREAD

**Issue by shakthimaan** [inhabitedtype/ocaml-session#26]
I require the following PR https://github.com/inhabitedtype/ocaml-session/pull/22 to build with Multicore OCaml 4.10. Can you please make a newer release `ocaml-session.0.4.2`, so that it does not depend on nocrypto? Thanks!

**Comment by talex5** [comment]
Hi, is there anything left to do to get the new ocaml-session release out? nocrypto is very obsolete at this point (last release 2017). Thanks!

**Comment by shakthimaan** [comment]
The issue can be closed. Thanks!

**Comment by seliopou** [comment]
Just cut a release: ocaml/opam-repository#19138.
